### ISSUE TITLE
retrieveJob response is larger than submitJob request resulting in a job that can't be processed when having large audio files

### ISSUE THREAD

**Issue by JulianFP** [JulianFP/project-W#46]
The problem is that retrieveJob returns the job in base64 encoding resulting in a larger response than the submitJob request (which contains the file in just binary). Since in the docker setup nginx is capped at 1GB this will result in jobs of certain sizes to be unable to be processed by the runner. The result of this can be one of the following:

- The backend crashes due to a service worker timeout triggered by gunicorn
- One of the threads of the runner crashes leaving it in a state where its still online but not processing any jobs. See https://github.com/JulianFP/project-W-runner/issues/20 for this

**Comment by dokempf** [comment]
What a stupid corner case. Good detective work!
